 variable "vpc-block" {}
 variable "env-variable" {}
 variable "availability_zone" {}
 variable "ami-id" {}
 variable "instance-type" {}
 variable "subnet1a-block" {}
 variable "subnet1b-block" {}
 variable "ssh-myip" {}
 variable "key-pair" {}
 variable "script-file" {}